Feature/user
sas2job/test-rails-api pull request #1
Opened 2021-05-06 10:50 UTC by sas2job

2021-05-06 11:18 UTC, alxekb requested changes

2021-05-06 11:18 UTC, alxekb commented on test/models/user_test.rb
> +end
@sas2job Please remove minitest 🙂

2021-05-06 11:18 UTC, alxekb commented on test/fixtures/users.yml
> +  password: MyString
Please remove fixtires, use factories instead @sas2job

2021-05-06 11:18 UTC, alxekb commented on test/controllers/api/v1/users_controller_test.rb
> +end
@sas2job same thing here 🙂

2021-05-06 15:00 UTC, sas2job commented on test/models/user_test.rb
> +end
It's removed.

2021-05-12 17:53 UTC, alxekb requested changes

2021-05-12 17:53 UTC, alxekb commented on app/controllers/api/v1/users_controller.rb
> +        if @user
```
ApiExceptionHandler.record_not_found if user.blank?

if user.destroy
  render
```

2021-05-12 17:53 UTC, alxekb commented on app/controllers/api/v1/users_controller.rb
> +        return render json: { errors: 'User not found.' } if @user.class == NilClass
```
@user.nil?
```

2021-05-12 17:53 UTC, alxekb commented on app/controllers/api/v1/users_controller.rb
> +        return render json: { errors: 'Password is empty.' } if params[:password] == ''
```
unless params[:password].present?
```

2021-05-15 15:23 UTC, sas2job commented on app/controllers/api/v1/users_controller.rb
> +        return render json: { errors: 'Password is empty.' } if params[:password] == ''
Fixed

2021-05-15 15:23 UTC, sas2job commented on app/controllers/api/v1/users_controller.rb
> +        return render json: { errors: 'User not found.' } if @user.class == NilClass
Fixed

2021-05-17 07:36 UTC, alxekb approved these changes
Please add json serializer

2021-05-18 08:08 UTC, closed without merging